--- 

- name: Install python MySQL connectors
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - mariadb-devel.x86_64
    - mariadb-libs.x86_64
    - mysql-connector-python.noarch
    - MySQL-python.x86_64
    - rsync.x86_64

- name: CreateDB for wordpress
  mysql_db:
    name: wordpress
    state: present

- name: Create database user for wordpress
  mysql_user:
    name: "{{ wordpress_user }}"
    password: "{{ wordpress_pass }}"
    priv: wordpress.*:ALL
    state: present

- name: Install wordpress packages
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - php-gd.x86_64

- name: Restart httpd
  sudo: yes
  service: name=httpd state=restarted

- include: wordpress.yml
